version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: pgdb
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg_password
    ports:
      - '5555:5432'
    volumes:
      - ./my-db:/var/lib/postgresql/data

volumes:
  pgdata:
